### ISSUE TITLE
SqL

### ISSUE THREAD

**Issue by TugaPowerROM** [AxelTronix/Gang-Mangement-ESX-GANGS-IMRPOVE-#1]
keep having erros on sql, missing the sql file to add to database?

**Comment by Bwashere** [comment]
Mhm First I would follow me on github lol. And This is a WIP. Its not done yet I am making it work with mysql-async


I could write the sql file tho hold up

**Comment by Bwashere** [comment]
> keep having erros on sql, missing the sql file to add to database?

Use my version :)

**Comment by AxelTronix** [comment]
> keep having erros on sql, missing the sql file to add to database?

Provide a SS please of the error

**Comment by Bwashere** [comment]
@AxelTronix How you gonna delete my comment when you didnt even add an sql file to the repo

**Comment by bradley1337** [comment]
Issue fixed in the latest version @TugaPowerROM
